config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  devise_for :users

  resources :books do
    resources :book_reviews, as: :reviews, except: [:show]
    resources :authors_books, as: :authors, only: [:new, :create, :destroy]
    resources :books_tags, as: :tags, only: [:new, :create, :destroy]
  end

  resources :authors
  resources :tags, except: [:show]

  namespace :admin do
    resources :user_roles, only: [:index, :update]
  end
end

app/controllers/authors_books_controller.rb
class AuthorsBooksController < ApplicationController
  before_action :find_book

  def new
    authorize @book, :update?
    set_author_select_options
  end

  def create
    authorize @book, :update?

    if @book.add_author(params[:author_id])
      flash[:notice] = 'Author added successfully.'
      redirect_to book_path(@book)
    else
      set_author_select_options
      flash.now[:alert] = 'Failed to add author!'
      render :new
    end
  end

  def destroy
    authorize @book, :update?

    if @book.remove_author(params[:id])
      flash[:notice] = 'Author removed successfully.'
    else
      flash[:alert] = 'Failed to remove author!'
    end

    redirect_to book_path(@book)
  end

  private

  def find_book
    @book = Book.find(params[:book_id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Book not found!'
    redirect_to books_path
  end

  def set_author_select_options
    @authors = Author.all.excluding_for_book(@book).only_id_and_name
  end
end

app/views/authors_books/_new_field.html.erb
<div class="field">
  <%= label_tag 'author_id', 'Author', class: 'label' %>

  <div class="control has-icons-left">
    <div class="select is-fullwidth">
      <%= select_tag 'author_id',
            options_from_collection_for_select(authors, :id, :name, params[:author_id]),
            prompt: 'Select author' %>
    </div>

    <span class="icon is-left">
      <i class="fas fa-pen-nib" aria-hidden="true"></i>
    </span>
  </div>

  <%= help_error_message(f, :new_book_author_id) %>
</div>

app/views/authors_books/new.html.erb
<h2 class="title">Add author</h2>

<%= form_with(model: @book, method: :post, url: book_authors_path(@book),
              html: { class: 'add-author-form box' }) do |f| %>

  <%= render 'new_field', f: f, authors: @authors %>

  <div class="field">
    <div class="control">
      <%= f.submit 'Save', class: 'button is-primary' %>
    </div>
  </div>
<% end %>