config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  devise_for :users

  resources :books do
    resources :book_reviews, as: :reviews, except: [:show]
    resources :authors_books, as: :authors, only: [:new, :create, :destroy]
    resources :books_tags, as: :tags, only: [:new, :create, :destroy]
  end

  resources :authors
  resources :tags, except: [:show]

  namespace :admin do
    resources :user_roles, only: [:index, :update]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch::Model
  include BookAuthorsConcern
  include BookTagsConcern

  ## Validations
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  ## Relationships
  has_many :book_reviews
  has_and_belongs_to_many :authors
  has_and_belongs_to_many :tags

  ## Scopes
  scope :search_for_index, -> (search_params = {}) do
    Books::Search.new(all.order(:title)).call(search_params)
  end

  pg_search_scope :fulltext_search, against: :title,
    using: { tsearch: { tsvector_column: 'tsv', dictionary: 'english' } }

  ## Instance methods
  def reviewed_by?(user)
    book_reviews.exists?(user_id: user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  rescue_from ActionController::ParameterMissing, with: :missing_book_params

  def index
    @search_params = search_params
    @books = Book.search_for_index(@search_params)
                 .includes(:authors, :tags)

    @user_reviews = BookReview.for_user(current_user)
                              .index_by(&:book_id)

    load_search_form_select_options
  end

  def show
    authorize @book

    @authors = @book.authors.only_id_and_name
    @tags = @book.tags.to_a
    @book_review = BookReview.find_by(user: current_user, book: @book) if current_user
  end

  def new
    @book = Book.new
    authorize @book
    load_author_select_options
  end

  def create
    @book = Book.new(book_params)
    authorize @book

    if @book.save_with_new_author(params[:author_id])
      flash[:notice] = 'Book created successfully.'
      redirect_to book_path(@book)
    else
      load_author_select_options
      flash.now[:alert] = 'Failed to create book!'
      render :new
    end
  end

  def edit
    authorize @book
  end

  def update
    authorize @book

    if @book.update(book_params)
      flash[:notice] = 'Book updated successfully.'
      redirect_to book_path(@book)
    else
      flash.now[:alert] = 'Failed to update book!'
      render :edit
    end
  end

  def destroy
    authorize @book

    @book.destroy!

    flash[:notice] = 'Book deleted successfully.'
    redirect_to books_path
  end

  private

  def find_book
    @book = Book.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Book not found!'
    redirect_to books_path
  end

  def search_params
    params.fetch(:search) { ActionController::Parameters.new }
          .permit(:title, :author_id, :tag_id)
  end

  def book_params
    params.require(:book).permit(:title, :description)
  end

  def load_search_form_select_options
    load_author_select_options
    load_tag_select_options
  end

  def load_author_select_options
    @authors = Author.all.only_id_and_name
  end

  def load_tag_select_options
    @tags = Tag.all
  end

  def missing_book_params
    flash[:alert] = 'Must supply book params!'

    if action_name == 'create'
      redirect_to new_book_path
    else
      redirect_to edit_book_path(@book)
    end
  end
end

app/views/books/_book_card.html.erb
<%- user_book_review = user_reviews[book.id] -%>
<div class="column is-one-third">
  <article class="card">
    <header class="card-header">
      <h4 class="card-header-title">
        <%= link_to book_path(book) do %>
          <span class="icon">
            <i class="fas fa-book" aria-hidden="true"></i>
          </span>
          <span class="book-title"><%= book.title %></span>
        <% end %>
      </h4>
    </header>
    <section class="card-content">
      <%= render 'authors/author_tags', authors: book.authors %>
      <%= render 'tags/book_tags', tags: book.tags %>

      <div class="content book-description">
        <%= simple_format(book.description) %>
      </div>

      <div class="book-review-info">
        <%= book_reviews_link(book) %>
      </div>
    </section>
    <% if user_signed_in? %>
      <footer class="card-footer">
        <% if user_book_review %>
          <%= link_to referred_book_review_path(book, user_book_review), class: 'card-footer-item' do %>
            <span class="icon">
              <i class="fas fa-check" aria-hidden="true"></i>
            </span>
            You've reviewed this book
          <% end %>
        <% else %>
          <%= link_to new_book_review_path(book), class: 'card-footer-item' do %>
            <span class="icon">
              <i class="fas fa-pencil-alt" aria-hidden="true"></i>
            </span>
            Add book review
          <% end %>
        <% end %>
      </footer>
    <% end %>
  </article>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, html: { class: 'book-form box' } ) do |f| %>
  <div class="field">
    <%= f.label :title, class: 'label' %>

    <div class="control has-icons-left">
      <%= f.text_field :title, class: 'input' %>

      <span class="icon is-left">
        <i class="fas fa-book" aria-hidden="true"></i>
      </span>
    </div>
    <%= help_error_message(f, :title) %>
  </div>

  <%# Allow users to set an initial author for new books.
    # After the book is persisted, more authors should be added using the
    # 'Add author' button on the book show page. %>
  <% if book.new_record? %>
    <%= render 'authors_books/new_field', f: f, authors: @authors %>
  <% end %>

  <div class="field">
    <%= f.label :description, class: 'label' %>

    <div class="control">
      <%= f.text_area :description, class: 'textarea' %>
    </div>
    <%= help_error_message(f, :description) %>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit "Save", class: 'button is-primary' %>
    </div>
  </div>
<% end %>

app/views/books/_search_form.html.erb
<%= form_with scope: :search, url: books_path, remote: false, method: :get,
      html: { id: 'book-search-form', class: 'panel' } do |f| %>
  <p class="panel-heading">Search books</p>

  <section class="panel-block">
    <div class="control has-icons-left">
      <%= f.text_field :title, class: 'input', value: search_params[:title],
              placeholder: 'Search by title...', autofocus: 'autofocus' %>
      <span class="icon is-left">
        <i class="fas fa-search" aria-hidden="true"></i>
      </span>
    </div>
  </section>

  <section class="panel-block">
    <div class="control has-icons-left">
      <div class="select is-fullwidth">
        <%= f.select :author_id,
              options_from_collection_for_select(authors, :id, :name, search_params[:author_id]),
              prompt: 'Search by author' %>
      </div>

      <span class="icon is-left">
        <i class="fas fa-pen-nib" aria-hidden="true"></i>
      </span>
    </div>
  </section>

  <section class="panel-block">
    <div class="control has-icons-left">
      <div class="select is-fullwidth">
        <%= f.select :tag_id,
              options_from_collection_for_select(tags, :id, :name, search_params[:tag_id]),
              prompt: 'Search by tag' %>
      </div>

      <span class="icon is-left">
        <i class="fas fa-tag" aria-hidden="true"></i>
      </span>
    </div>
  </section>

  <section class="panel-block search-button">
    <div class="buttons">
      <%= link_to 'Reset', books_path, class: 'button' %>
      <%= f.submit 'Search', class: 'button is-primary' %>
    </div>
  </section>
<% end %>

app/views/books/edit.html.erb
<h2 class="title">Edit book</h2>

<%= render 'form', book: @book %>

app/views/books/index.html.erb
<h1 class="title">Books</h1>

<% if user_signed_in? %>
  <div class="buttons">
    <% if policy(Book).create? %>
      <%= link_to new_book_path, class: "button" do %>
        <span class="icon">
          <i class="fas fa-plus" aria-hidden="true"></i>
        </span>
        <span>Add new book</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= render 'search_form', search_params: @search_params,
                          tags: @tags,
                          authors: @authors %>

<section class="books columns is-multiline">
  <%= render collection: @books, partial: 'book_card', as: :book,
        locals: { user_reviews: @user_reviews }  %>
</section>

app/views/books/new.html.erb
<h2 class="title">New book</h2>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<article class="box">
  <div class="level">
    <div class="level-left">
      <h2 class="level-item book-title"><%= @book.title %></h2>
    </div>
    <div class="level-right">
      <div class="level-item buttons book-actions">
        <% if @book.reviewed_by?(current_user) %>
          <%= link_to referred_book_review_path(@book, @book_review), class: 'button is-primary' do %>
            <span class="icon">
              <i class="fas fa-check" aria-hidden="true"></i>
            </span>
            <span>Reviewed</span>
          <% end %>
        <% elsif book_review_policy(@book).create? %>
          <%= link_to new_book_review_path(@book), class: 'button is-primary' do %>
            <span class="icon">
              <i class="fas fa-pencil-alt" aria-hidden="true"></i>
            </span>
            <span>Review book</span>
          <% end %>
        <% end %>
        <% if policy(@book).update? %>
          <%= link_to edit_book_path(@book), class: 'button is-info' do %>
            <span class="icon">
              <i class="fas fa-edit" aria-hidden="true"></i>
            </span>
            <span>Edit <span class="is-sr-only">book</span></span>
          <% end %>
        <% end %>
        <% if policy(@book).destroy? %>
          <%= link_to book_path(@book), class: 'button is-danger',
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this book?' } do %>
            <span class="icon">
              <i class="fas fa-times" aria-hidden="true"></i>
            </span>
            <span>Delete <span class="is-sr-only">book</span></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="level">
    <div class="level-left">
      <div class="level-item">
        <%= render 'authors/author_tags',
              authors: @authors,
              book: @book,
              allow_delete_tags: policy(@book).update?  %>
      </div>

      <% if @tags.any? %>
        <div class="level-item">
          <%= render 'tags/book_tags',
                tags: @tags,
                book: @book,
                allow_delete_tags: policy(@book).update?  %>
        </div>
      <% end %>
    </div>

    <% if signed_in_as_staff? %>
      <div class="level-right ml-3">
        <div class="level-item buttons">
          <% if policy(@book).update? %>
            <%= link_to new_book_author_path(@book), class: 'button is-primary' do %>
              <%= icon_span('fas fa-pen-nib') %>
              <span>Add author</span>
            <% end %>
            <%= link_to new_book_tag_path(@book), class: 'button is-primary' do %>
              <%= icon_span('fas fa-tag') %>
              <span>Add tag</span>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <section class="book-description">
    <%= simple_format(@book.description) %>
  </section>
</article>