config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  devise_for :users

  resources :books do
    resources :book_reviews, as: :reviews, except: [:show]
    resources :authors_books, as: :authors, only: [:new, :create, :destroy]
    resources :books_tags, as: :tags, only: [:new, :create, :destroy]
  end

  resources :authors
  resources :tags, except: [:show]

  namespace :admin do
    resources :user_roles, only: [:index, :update]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  ## Validations
  validates :name, presence: true
  validates_uniqueness_of :name, rescue_from_duplicate: true

  ## Relationships
  has_and_belongs_to_many :books

  ## Scopes
  scope :for_index, ->() { order(:name) }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_tag, only: [:edit, :update, :destroy]
  rescue_from ActionController::ParameterMissing, with: :missing_tag_params

  def index
    @tags = Tag.for_index
  end

  def new
    @tag = Tag.new
    authorize @tag
  end

  def create
    @tag = Tag.new(tag_params)
    authorize @tag

    if @tag.save
      flash[:notice] = 'Tag created successfully.'
      redirect_to tags_path
    else
      flash.now[:alert] = 'Failed to create tag!'
      render :new
    end
  end

  def edit
    authorize @tag
  end

  def update
    authorize @tag

    if @tag.update(tag_params)
      flash[:notice] = 'Tag updated successfully.'
      redirect_to tags_path
    else
      flash.now[:alert] = 'Failed to update tag!'
      render :edit
    end
  end

  def destroy
    authorize @tag

    @tag.destroy

    flash[:notice] = 'Tag deleted successfully.'
    redirect_to tags_path
  end

  private

  def find_tag
    @tag = Tag.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Tag not found!'
    redirect_to tags_path
  end

  def tag_params
    params.require(:tag).permit(:name, :icon, :color)
  end

  def missing_tag_params
    flash[:alert] = 'Must supply tag params!'
    redirect_to new_tag_path
  end
end

app/views/tags/_book_tags.html.erb
<%- allow_delete_tags = local_assigns.fetch(:allow_delete_tags, false) -%>
<section class="book-tags mb-3">
  <div class="tags">
    <% tags.each do |tag| %>
      <p class="tag is-medium" id="book-tag-<%= tag.id %>" style="<%= display_tag_css_style(tag) %>">
        <%= icon_span(tag.icon.presence || 'fas fa-tag') %>
        <span class="tag-name"><%= tag.name %></span>

        <% if allow_delete_tags %>
          <%= link_to book_tag_path(book, tag),
                class: 'delete is-small', method: :delete,
                data: { confirm: 'Are you sure you want to remove this tag?' } do %>
            <span class="is-sr-only">Remove tag</span>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
</section>

app/views/tags/_form.html.erb
<%= form_with(model: tag, html: { class: 'tag-form box' }) do |f| %>
  <div class="field">
    <%= f.label :name, class: 'label' %>

    <div class="control has-icons-left">
      <%= f.text_field :name, class: 'input' %>

      <span class="icon is-left">
        <i class="fas fa-tag" aria-hidden="true"></i>
      </span>
    </div>
    <%= help_error_message(f, :name) %>
  </div>

  <div class="field">
    <%= f.label :icon, class: 'label' %>

    <div class="control has-icons-left">
      <%= f.text_field :icon, class: 'input', list: 'tag-icon-options-list' %>

      <span class="icon is-left">
        <i class="fas fa-icons" aria-hidden="true"></i>
      </span>
    </div>
    <%= help_error_message(f, :icon) %>
    <span class="help is-info">
      For awesome icons check out <a href="https://fontawesome.com/v5.15/icons">Font Awesome</a>
    </span>
  </div>

  <div class="field">
    <%= f.label :color, class: 'label' %>

    <div class="control has-icons-left">
      <%= f.color_field :color, class: 'input' %>

      <span class="icon is-left">
        <i class="fas fa-tint" aria-hidden="true"></i>
      </span>
    </div>
    <%= help_error_message(f, :color) %>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit 'Save', class: 'button is-primary' %>
    </div>
  </div>

  <%= tag_icon_options_list %>
<% end %>

app/views/tags/edit.html.erb
<h2 class="title">Edit tag</h2>

<%= render 'form', tag: @tag %>

app/views/tags/index.html.erb
<%# Avoid having to check current user for each table row %>
<%- signed_in_as_staff = signed_in_as_staff? -%>

<h1 class="title">Tags</h1>

<% if user_signed_in? %>
  <div class="buttons">
    <% if policy(Tag).create? %>
      <%= link_to new_tag_path, class: 'button' do %>
        <span class="icon">
          <i class="fas fa-plus" aria-hidden="true"></i>
        </span>
        <span>Add new tag</span>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="box">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <% if signed_in_as_staff %>
          <th scope="col">Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <tr id="tag-row-<%= tag.id%>" class="tag-row">
          <th scope="row" class="tag-name">
            <%= display_tag(tag) %>
          </th>
          <% if signed_in_as_staff %>
            <td>
              <div class="buttons">
                <% if policy(tag).update? %>
                  <%= link_to edit_tag_path(tag), class: 'button is-info is-small' do %>
                    <span class="icon">
                      <i class="fas fa-edit" aria-hidden="true"></i>
                    </span>
                    <span>Edit<span class="is-sr-only"> tag</span></span>
                  <% end %>
                <% end %>
                <% if policy(tag).destroy? %>
                  <%= link_to tag_path(tag), class: 'button is-danger is-small',
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this tag?' } do %>
                    <span class="icon">
                      <i class="fas fa-times" aria-hidden="true"></i>
                    </span>
                    <span>Delete<span class="is-sr-only"> tag</span></span>
                  <% end %>
                <% end %>
              </div>
            </td>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tags/new.html.erb
<h2 class="title">New tag</h2>

<%= render 'form', tag: @tag %>