config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  devise_for :users

  resources :books do
    resources :book_reviews, as: :reviews, except: [:show]
    resources :authors_books, as: :authors, only: [:new, :create, :destroy]
    resources :books_tags, as: :tags, only: [:new, :create, :destroy]
  end

  resources :authors
  resources :tags, except: [:show]

  namespace :admin do
    resources :user_roles, only: [:index, :update]
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :allow_only_admin
  skip_after_action :verify_authorized

  private

  def allow_only_admin
    unless user_signed_in? && current_user.admin?
      flash[:alert] = 'Admin area is restricted!'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  after_action :verify_authorized, except: :index, unless: :devise_controller?

  before_action :authenticate_user!

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform that action.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def signed_in_as_staff?
    user_signed_in? && current_user.staff?
  end

  def navbar_brand(label)
    css_class = ['navbar-item']
    css_class << 'is-active' if current_page?(root_path)

    link_to label, root_path, class: css_class
  end

  def navbar_link(label, path, icon_class)
    css_class = ['navbar-item']
    css_class << 'is-active' if current_page?(path)

    link_to path, class: css_class do
      concat(tag.span(class: 'icon') do
        tag.i class: icon_class, aria: { hidden: 'true' }
      end)
      concat(tag.span label)
    end
  end
end

app/views/application/_navbar.html.erb
<nav id="main-navbar" class="navbar" role="navigation" aria-label="main navigation"
    data-controller="navbar" >
  <div class="navbar-brand">
    <%= navbar_brand('BookLists') %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
        data-action="navbar#toggleMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu" data-navbar-target="menu">
    <div class="navbar-start">
      <%= navbar_link('Books', books_path, 'fas fa-book') %>
      <%= navbar_link('Authors', authors_path, 'fas fa-pen-nib') %>
      <%= navbar_link('Tags', tags_path, 'fas fa-tag') %>
    </div>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <div id="admin-links" class="navbar-item has-dropdown is-hoverable">
            <span class="navbar-link">Admin</span>

            <div class="navbar-dropdown">
              <%= link_to admin_user_roles_path, class: 'navbar-item' do %>
                <span class="icon">
                  <i class="fas fa-user-tie" aria-hidden="true"></i>
                </span>
                <span>User roles</span>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="navbar-item">
          <span class="has-text-weight-bold"><%= current_user.email %></span>
        </div>
        <%= link_to 'Sign out', destroy_user_session_path, class: 'navbar-item',
              method: :delete %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: 'navbar-item' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-item' %>
      <% end %>
    </div>
  </div>
</nav>